[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.52.2",
    "flask>=3.1.1",
    "flask-cors>=6.0.0",
    "openai>=1.82.1",
    "requests>=2.32.3",
]
